[package]
name = "mug"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
ariadne = "0.6.0"
chumsky = "0.11.2"
cranelift = { version = "0.126", features = ["module", "object"] }
im = "15.1.0"
internment = "0.8.6"
logos = "0.15.1"
target-lexicon = "0.13.3"
tempfile = "3.23.0"
